### ISSUE TITLE
java.lang.NoClassDefFoundError with gradle 3.3

### ISSUE THREAD

**Issue by rameshselvaraj** [stevesaliman/gradle-cobertura-plugin#128]
Recently I have changed gradle version from 2.14.1 to 3.3 for my plugin development. I got following error for below cobertura configuration.
Please support me what could be the issue. 

$./gradlew clean assemble uploadArchive cobertura
:coberturaReport UP-TO-DATE
:instrument
Cobertura 2.1.1 - GNU GPL License (NO WARRANTY) - See COPYRIGHT file
Unable to instrument file /home/xyz.class
java.lang.NoClassDefFoundError: org/gradle/process/ProcessForkOptions
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
...
Unable to instrument file /home/xyz1.class
java.lang.NoClassDefFoundError: org/gradle/util/Configurable
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467
...

...

:copyCoberturaDatafile
:compileTestJava UP-TO-DATE
:compileTestGroovy
:processTestResources UP-TO-DATE
:testClasses
:test
....
....
:generateCoberturaReport
Report time: 138ms
Report time: 65ms
:performCoverageCheck SKIPPED
:cobertura

BUILD SUCCESSFUL
------------------------------------------------------------------
Gradle version:
gradle-3.3-bin.zip

build.gradle:
buildscript {
    repositories {
      ...
        dependencies {
            classpath 'net.saliman:gradle-cobertura-plugin:2.4.0' //works with 2.14.1, but got above error with gradle 3.3
        }
    }
}

apply plugin: 'groovy'
apply plugin: 'cobertura'

cobertura {
    coverageFormats = ['html', 'xml']
    coverageIgnoreTrivial = true
    coverageIgnores = ['org.slf4j.Logger.*']
    coverageReportDir = new File("$buildDir/reports/cobertura")
}

Please let me know if you need more information.

**Comment by stevesaliman** [comment]
I can't see anything obvious from what I see.  The part that stands out is that it is complaining about classes that are a part of Gradle itself.  The two classes mentioned are still part of Gradle as of version 3.3, so I'm not sure why there would be a complaint. 

I suspect something is going on with your classpath, but I'm not sure what it could be.  Does your project declare any dependency on the Gradle API?

**Comment by rameshselvaraj** [comment]
Thank you for your quick support,
>>Does your project declare any dependency on the Gradle API?
Yes, declared like below.
dependencies {
    compile gradleApi()
    ....
}
I have used --debug option with gradle command, I can see classpath is set as below.
--------------------------------
From log:
-XDuseUnsharedTable=true
12:28:59.127 [DEBUG] [org.gradle.process.internal.daemon.WorkerDaemonStarter] Starting Gradle worker daemon with fork options DaemonForkOptions{minHeapSize=null, maxHeapSize=null, jvmArgs=[], classpath=[/home/USERS/1234/.gradle/wrapper/dists/gradle-3.3-bin/egzetjbbgm57v4iqk61zle5ev/gradle-3.3/lib/groovy-all-2.4.7.jar, /home/USERS/1234/.gradle/wrapper/dists/gradle-3.3-bin/egzetjbbgm57v4iqk61zle5ev/gradle-3.3/lib/ant-1.9.6.jar, /home/USERS/1234/.gradle/wrapper/dists/gradle-3.3-bin/egzetjbbgm57v4iqk61zle5ev/gradle-3.3/lib/ant-launcher-1.9.6.jar]}.
---------------------

**Comment by rameshselvaraj** [comment]
Unfortunately I can't provide full log as of now, I have edited & suppressed log then attached here, I hope this will be helpful. Thank you for understanding.
[cobertura_debuglog2.txt](https://github.com/stevesaliman/gradle-cobertura-plugin/files/740936/cobertura_debuglog2.txt)

**Comment by stevesaliman** [comment]
I'm still not positive what is going on, but I did see a dependency on ```com.android.tools.build:gradle-core:2.3.0-beta2``` in the log.  The pom for that artifact (or the 2.2.0 version which is the latest release), brings in a gradle API.  My guess is that there is a conflict between the Gradle api that your artifact is including in and the version of gradle that you are actually running.  The documentation for the Android Studio Gradle plugin does mention Gradle 2 and not gradle 3, but just having 2 sets of Gradle classes in the classpath might be enough to confuse things.

**Comment by rameshselvaraj** [comment]
I am sure plugin 2.3.0-beta2 requires gradle 3.3, also confirmed by removing .gradle folders.
Following log observed during clean build
[Generating JAR file 'gradle-api-3.3.jar']

**Comment by stevesaliman** [comment]
Gradle 3.3 generates that jar when you run it for the first time after deleting the .gradle folders.  It is not connected to any dependencies of your project.  If you run ```gradle dependencies``` I think you will find that a Gradle 2.x API is being brought in, though your ```compile gradleApi()``` dependency in the project might be updating it to 3.3...

In the end I still think there is confusion between the different Gradle classes in your build...

**Comment by rameshselvaraj** [comment]
Thank you for the information, with ./gradlew dependencies I can see gradle-api:2.3.0-beta2 is used.
[|         +--- com.android.tools.build:gradle-api:2.3.0-beta2]
>>there is confusion between the different Gradle classes in your build...
   I will analyse this.

**Comment by woailuo1218** [comment]
how to solve the problem

**Comment by thadguidry** [comment]
I have updated the Wiki with [Gradle usage and Jenkins](https://github.com/stevesaliman/gradle-cobertura-plugin/wiki#gradle-usage-and-jenkins) section and a new [Troubleshooting](https://github.com/stevesaliman/gradle-cobertura-plugin/wiki#troubleshooting) section to provide info on how to resolve these kinds of problems with instrumentation in general.

Getters/Setters might be getting in your way, so consulting that Troubleshooting section.

**Comment by thadguidry** [comment]
@stevesaliman your welcome Steve :)
